# 25 May 2024

# done
# jbsub -q platform -name const-deepseek-coder-33b-instruct-colbert-1-rand -mem 128G -cores 1x2+2  -require a100_80gb -err /dccstor/rhassistant/platform_training/logs/const-deepseek-coder-33b-instruct-colbert-1-rand.err -out /dccstor/rhassistant/platform_training/logs/const-deepseek-coder-33b-instruct-colbert-1-rand.out python /dccstor/rhassistant/mehant/paper/constrain_gen_pipeline_codellama/guidance_pipeline/testing.py /dccstor/rhassistant/platform_training/models/deepseek-coder-33b-instruct /dccstor/rhassistant/mehant/paper/random_slit_85_15/random_85_15_split_test_ir_inf_clean.parquet /dccstor/rhassistant/mehant/paper/random_slit_85_15/deepseek-coder-33b-instruct-colbert-top-1-const.parquet 1

# running
# jbsub -q platform -name const-starcoder2-15b-instruct-colbert-1-rand -mem 128G -cores 1x2+2  -require a100_80gb -err /dccstor/rhassistant/platform_training/logs/const-starcoder2-15b-instruct-colbert-1-rand.err -out /dccstor/rhassistant/platform_training/logs/const-starcoder2-15b-instruct-colbert-1-rand.out python /dccstor/rhassistant/mehant/paper/constrain_gen_pipeline_codellama/guidance_pipeline/testing.py /dccstor/rhassistant/platform_training/models/starcoder2-15b-instruct-v0.1 /dccstor/rhassistant/mehant/paper/random_slit_85_15/random_85_15_split_test_ir_inf_clean.parquet /dccstor/rhassistant/mehant/paper/random_slit_85_15/starcoder2-15b-instruct-colbert-top-1-const.parquet 1

# jbsub -q platform -name const-codellama-34b-colbert-1-rand -mem 128G -cores 1x2+2  -require a100_80gb -err /dccstor/rhassistant/platform_training/logs/const-codellama-34b-colbert-1-rand.err -out /dccstor/rhassistant/platform_training/logs/const-codellama-34b-colbert-1-rand.out python /dccstor/rhassistant/mehant/paper/constrain_gen_pipeline_codellama/guidance_pipeline/testing.py codellama/CodeLlama-34b-Instruct-hf /dccstor/rhassistant/mehant/paper/random_slit_85_15/random_85_15_split_test_ir_inf_clean.parquet /dccstor/rhassistant/mehant/paper/random_slit_85_15/codellama-34b-colbert-top-1-const.parquet 1

# jbsub -q platform -name const-codellama-34b-colbert-3-rand -mem 128G -cores 1x2+2  -require a100_80gb -err /dccstor/rhassistant/platform_training/logs/const-codellama-34b-colbert-3-rand.err -out /dccstor/rhassistant/platform_training/logs/const-codellama-34b-colbert-3-rand.out python /dccstor/rhassistant/mehant/paper/constrain_gen_pipeline_codellama/guidance_pipeline/testing.py codellama/CodeLlama-34b-Instruct-hf /dccstor/rhassistant/mehant/paper/random_slit_85_15/random_85_15_split_test_ir_inf_clean.parquet /dccstor/rhassistant/mehant/paper/random_slit_85_15/codellama-34b-ft-colbert-top-3-const.parquet 3

# jbsub -q platform -name const-codellama-34b-colbert-10-rand -mem 128G -cores 1x2+2  -require a100_80gb -err /dccstor/rhassistant/platform_training/logs/const-codellama-34b-colbert-10-rand.err -out /dccstor/rhassistant/platform_training/logs/const-codellama-34b-colbert-10-rand.out python /dccstor/rhassistant/mehant/paper/constrain_gen_pipeline_codellama/guidance_pipeline/testing.py codellama/CodeLlama-34b-Instruct-hf /dccstor/rhassistant/mehant/paper/random_slit_85_15/random_85_15_split_test_ir_inf_clean.parquet /dccstor/rhassistant/mehant/paper/random_slit_85_15/codellama-34b-ft-colbert-top-10-const.parquet 10


# jbsub -q platform -name const-codellama-7b-colbert-1-rand -mem 128G -cores 1x1+1  -require a100_80gb -err /dccstor/rhassistant/platform_training/logs/const-codellama-7b-colbert-1-rand.err -out /dccstor/rhassistant/platform_training/logs/const-codellama-7b-colbert-1-rand.out python /dccstor/rhassistant/mehant/paper/constrain_gen_pipeline_codellama/guidance_pipeline/testing.py /dccstor/rhassistant/platform_training/training/codellama-7b/nl2yaml/ft_random/epochs/epoch-2.0/ /dccstor/rhassistant/mehant/paper/random_slit_85_15/random_85_15_split_test_ir_inf_clean.parquet /dccstor/rhassistant/mehant/paper/random_slit_85_15/codellama-7b-ft-colbert-top-1-const.parquet 1

# jbsub -q platform -name const-codellama-7b-colbert-3-rand -mem 128G -cores 1x1+1  -require a100_80gb -err /dccstor/rhassistant/platform_training/logs/const-codellama-7b-colbert-3-rand.err -out /dccstor/rhassistant/platform_training/logs/const-codellama-7b-colbert-3-rand.out python /dccstor/rhassistant/mehant/paper/constrain_gen_pipeline_codellama/guidance_pipeline/testing.py /dccstor/rhassistant/platform_training/training/codellama-7b/nl2yaml/ft_random/epochs/epoch-2.0/ /dccstor/rhassistant/mehant/paper/random_slit_85_15/random_85_15_split_test_ir_inf_clean.parquet /dccstor/rhassistant/mehant/paper/random_slit_85_15/codellama-7b-ft-colbert-top-3-const.parquet 3

# jbsub -q platform -name const-codellama-7b-colbert-10-rand -mem 128G -cores 1x1+1  -require a100_80gb -err /dccstor/rhassistant/platform_training/logs/const-codellama-7b-colbert-10-rand.err -out /dccstor/rhassistant/platform_training/logs/const-codellama-7b-colbert-10-rand.out python /dccstor/rhassistant/mehant/paper/constrain_gen_pipeline_codellama/guidance_pipeline/testing.py /dccstor/rhassistant/platform_training/training/codellama-7b/nl2yaml/ft_random/epochs/epoch-2.0/ /dccstor/rhassistant/mehant/paper/random_slit_85_15/random_85_15_split_test_ir_inf_clean.parquet /dccstor/rhassistant/mehant/paper/random_slit_85_15/codellama-7b-ft-colbert-top-10-const.parquet 10


# jbsub -q platform -name const-codellama-7b-colbert-base-1-rand -mem 128G -cores 1x1+1  -require a100_80gb -err /dccstor/rhassistant/platform_training/logs/const-codellama-7b-colbert-base-1-rand.err -out /dccstor/rhassistant/platform_training/logs/const-codellama-7b-colbert-base-1-rand.out python /dccstor/rhassistant/mehant/paper/constrain_gen_pipeline_codellama/guidance_pipeline/testing.py /dccstor/rhassistant/platform_training/models/codellama/CodeLlama-7b-hf /dccstor/rhassistant/mehant/paper/random_slit_85_15/random_85_15_split_test_ir_inf_clean.parquet /dccstor/rhassistant/mehant/paper/random_slit_85_15/codellama-7b-base-colbert-top-1-const.parquet 1
