# June 11 2024

jbsub -q platform -name const-starcoder2-15b-instruct-v0.1-rand-ir-only -mem 128G -cores 1x2+2  -require a100_80gb -err /dccstor/rhassistant/platform_training/logs/const-starcoder2-15b-instruct-v0.1-rand-ir-only.err -out /dccstor/rhassistant/platform_training/logs/const-starcoder2-15b-instruct-v0.1-rand-ir-only.out python /dccstor/rhassistant/mehant/paper/constrain_gen_pipeline_codellama/guidance_pipeline/gen_ir_only.py /dccstor/rhassistant/platform_training/models/starcoder2-15b-instruct-v0.1 /dccstor/rhassistant/mehant/paper/random_slit_85_15/random_85_15_split_test_ir_inf_clean.parquet /dccstor/rhassistant/mehant/paper/random_slit_85_15/starcoder2-15b-instruct-v0.1-colbert-top-1-const-ir-only.parquet 1


# jbsub -q platform -name const-codellama-34b-colbert-1-rand-ir-only -mem 128G -cores 1x2+2  -require a100_80gb -err /dccstor/rhassistant/platform_training/logs/const-codellama-34b-colbert-1-rand-ir-only.err -out /dccstor/rhassistant/platform_training/logs/const-codellama-34b-colbert-1-rand-ir-only.out python /dccstor/rhassistant/mehant/paper/constrain_gen_pipeline_codellama/guidance_pipeline/gen_ir_only.py codellama/CodeLlama-34b-Instruct-hf /dccstor/rhassistant/mehant/paper/random_slit_85_15/random_85_15_split_test_ir_inf_clean.parquet /dccstor/rhassistant/mehant/paper/random_slit_85_15/codellama-34b-colbert-top-1-const-ir-only.parquet 1

# jbsub -q platform -name const-codellama-34b-colbert-3-rand-ir-only -mem 128G -cores 1x2+2  -require a100_80gb -err /dccstor/rhassistant/platform_training/logs/const-codellama-34b-colbert-3-rand-ir-only.err -out /dccstor/rhassistant/platform_training/logs/const-codellama-34b-colbert-3-rand-ir-only.out python /dccstor/rhassistant/mehant/paper/constrain_gen_pipeline_codellama/guidance_pipeline/gen_ir_only.py codellama/CodeLlama-34b-Instruct-hf /dccstor/rhassistant/mehant/paper/random_slit_85_15/random_85_15_split_test_ir_inf_clean.parquet /dccstor/rhassistant/mehant/paper/random_slit_85_15/codellama-34b-colbert-top-3-const-ir-only.parquet 3

# jbsub -q platform -name const-codellama-34b-colbert-10-rand-ir-only -mem 128G -cores 1x2+2  -require a100_80gb -err /dccstor/rhassistant/platform_training/logs/const-codellama-34b-colbert-10-rand-ir-only.err -out /dccstor/rhassistant/platform_training/logs/const-codellama-34b-colbert-10-rand-ir-only.out python /dccstor/rhassistant/mehant/paper/constrain_gen_pipeline_codellama/guidance_pipeline/gen_ir_only.py codellama/CodeLlama-34b-Instruct-hf /dccstor/rhassistant/mehant/paper/random_slit_85_15/random_85_15_split_test_ir_inf_clean.parquet /dccstor/rhassistant/mehant/paper/random_slit_85_15/codellama-34b-colbert-top-10-const-ir-only.parquet 10



# jbsub -q platform -name const-codellama-7b-colbert-1-rand-ir-only -mem 128G -cores 1x1+1  -require a100_80gb -err /dccstor/rhassistant/platform_training/logs/const-codellama-7b-colbert-1-rand-ir-only.err -out /dccstor/rhassistant/platform_training/logs/const-codellama-7b-colbert-1-rand-ir-only.out python /dccstor/rhassistant/mehant/paper/constrain_gen_pipeline_codellama/guidance_pipeline/gen_ir_only.py /dccstor/rhassistant/platform_training/training/codellama-7b/nl2yaml/ft_random/epochs/epoch-2.0/ /dccstor/rhassistant/mehant/paper/random_slit_85_15/random_85_15_split_test_ir_inf_clean.parquet /dccstor/rhassistant/mehant/paper/random_slit_85_15/codellama-7b-ft-colbert-top-1-const-ir-only.parquet 1

# jbsub -q platform -name const-codellama-7b-colbert-3-rand-ir-only -mem 128G -cores 1x1+1  -require a100_80gb -err /dccstor/rhassistant/platform_training/logs/const-codellama-7b-colbert-3-rand-ir-only.err -out /dccstor/rhassistant/platform_training/logs/const-codellama-7b-colbert-3-rand-ir-only.out python /dccstor/rhassistant/mehant/paper/constrain_gen_pipeline_codellama/guidance_pipeline/gen_ir_only.py /dccstor/rhassistant/platform_training/training/codellama-7b/nl2yaml/ft_random/epochs/epoch-2.0/ /dccstor/rhassistant/mehant/paper/random_slit_85_15/random_85_15_split_test_ir_inf_clean.parquet /dccstor/rhassistant/mehant/paper/random_slit_85_15/codellama-7b-ft-colbert-top-3-const-ir-only.parquet 3

# jbsub -q platform -name const-codellama-7b-colbert-10-rand-ir-only -mem 128G -cores 1x1+1  -require a100_80gb -err /dccstor/rhassistant/platform_training/logs/const-codellama-7b-colbert-10-rand-ir-only.err -out /dccstor/rhassistant/platform_training/logs/const-codellama-7b-colbert-10-rand-ir-only.out python /dccstor/rhassistant/mehant/paper/constrain_gen_pipeline_codellama/guidance_pipeline/gen_ir_only.py /dccstor/rhassistant/platform_training/training/codellama-7b/nl2yaml/ft_random/epochs/epoch-2.0/ /dccstor/rhassistant/mehant/paper/random_slit_85_15/random_85_15_split_test_ir_inf_clean.parquet /dccstor/rhassistant/mehant/paper/random_slit_85_15/codellama-7b-ft-colbert-top-10-const-ir-only.parquet 10


# jbsub -q platform -name const-codellama-7b-colbert-base-1-rand-ir-only -mem 128G -cores 1x1+1  -require a100_80gb -err /dccstor/rhassistant/platform_training/logs/const-codellama-7b-colbert-base-1-rand-ir-only.err -out /dccstor/rhassistant/platform_training/logs/const-codellama-7b-colbert-base-1-rand-ir-only.out python /dccstor/rhassistant/mehant/paper/constrain_gen_pipeline_codellama/guidance_pipeline/gen_ir_only.py /dccstor/rhassistant/platform_training/models/codellama/CodeLlama-7b-hf /dccstor/rhassistant/mehant/paper/random_slit_85_15/random_85_15_split_test_ir_inf_clean.parquet /dccstor/rhassistant/mehant/paper/random_slit_85_15/codellama-7b-base-colbert-top-1-const-ir-only.parquet 1


